name: "DataWarehouse"
version: "1.0.0"
profile: "DataWarehouse"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

# Schema Struktur Folder
models:
  DataWarehouse:
    bronze:
      +materialized: table
    silver:
      +materialized: table
    gold:
      +materialized: table

# Bronze type data
seeds:
  DataWarehouse:
    crm_cust_info:
      column_types:
        cst_id: INT
        cst_key: VARCHAR
        cst_firstname: VARCHAR
        cst_lastname: VARCHAR
        cst_marital_status: VARCHAR
        cst_gndr: VARCHAR
        cst_create_date: DATE

    crm_prd_info:
      column_types:
        prd_id: INT
        prd_key: VARCHAR
        prd_nm: VARCHAR
        prd_cost: INT
        prd_line: VARCHAR
        prd_start_dt: TIMESTAMP
        prd_end_dt: TIMESTAMP

    crm_sales_details:
      column_types:
        sls_ord_num: VARCHAR
        sls_prd_key: VARCHAR
        sls_cust_id: INT
        sls_order_dt: INT
        sls_ship_dt: INT
        sls_due_dt: INT
        sls_sales: INT
        sls_quantity: INT
        sls_price: INT

    erp_loc_a101:
      column_types:
        cid: VARCHAR
        cntry: VARCHAR

    erp_cust_az12:
      column_types:
        cid: VARCHAR
        bdate: DATE
        gen: VARCHAR

    erp_px_cat_g1v2:
      column_types:
        id: VARCHAR
        cat: VARCHAR
        subcat: VARCHAR
        maintenance: VARCHAR
