version: 2

models:
  - name: bronze_crm_cust_info
    description: >
      Raw customer information ingested from source `cust_info`. This model handles basic type casting and standardization.
    columns:
      - name: cst_id
        description: Unique identifier for customer.
        tests: [not_null, unique]
      - name: cst_key
        description: Business key for customer.
        tests: [not_null]
      - name: cst_firstname
        description: Customer first name.
      - name: cst_lastname
        description: Customer last name.
      - name: cst_marital_status
        description: Customer marital status.
      - name: cst_gndr
        description: Customer gender.
      - name: cst_create_date
        description: Customer creation date.

  - name: bronze_crm_prd_info
    description: >
      Raw product information ingested from `prd_info`. This model applies initial data cleaning.
    columns:
      - name: prd_id
        description: Unique product ID.
        tests: [not_null, unique]
      - name: prd_key
        description: Product business key.
        tests: [not_null]
      - name: prd_nm
        description: Product name.
      - name: prd_cost
        description: Product cost.
      - name: prd_line
        description: Product line.
      - name: prd_start_dt
        description: Product active start date.
      - name: prd_end_dt
        description: Product active end date.

  - name: bronze_crm_sales_details
    description: >
      Raw sales transactions including sales amount, quantity, and price for each transaction.
    columns:
      - name: sls_sales
        description: Total sales value.
      - name: sls_quantity
        description: Quantity sold.
      - name: sls_price
        description: Unit price.

  - name: bronze_erp_cust_az12
    description: >
      Raw ERP customer data from system AZ12 including birth date and gender.
    columns:
      - name: cid
        description: Customer ID from ERP.
        tests: [not_null, unique]
      - name: bdate
        description: Customer birth date.
      - name: gen
        description: Customer gender.

  - name: bronze_erp_loc_a101
    description: >
      ERP location data from system A101 for warehouse or store site information.
    columns:
      - name: loc_id
        description: Unique location identifier.
      - name: loc_name
        description: Location name.
      - name: loc_type
        description: Type of location (e.g. warehouse, store).

  - name: bronze_erp_px_cat_g1v2
    description: >
      ERP pricing category from system G1V2.
    columns:
      - name: cat_id
        description: Category ID.
      - name: cat_name
        description: Category name.

  - name: silver_crm_cust_info
    description: >
      Cleaned customer data including standardized gender and marital status formats.

  - name: silver_crm_prd_info
    description: >
      Cleaned product data with validated date range and cost values.

  - name: silver_crm_sales_details
    description: >
      Validated and enriched sales data, ensuring logical consistency in sales_amount = quantity * price.

  - name: silver_erp_cust_az12
    description: >
      Cleaned ERP customer records from system AZ12 with standardized birth date range.

  - name: silver_erp_loc_a101
    description: >
      Location information enriched with standardized type and name formats.

  - name: silver_erp_px_cat_g1v2
    description: >
      Refined pricing category reference table for G1V2 product classification.

  - name: dim_customers
    description: >
      Dimension table containing enriched and deduplicated customer profiles.
    columns:
      - name: customer_key
        description: Surrogate key for customers.
        tests: [not_null, unique]

  - name: dim_products
    description: >
      Dimension table for enriched product data used in analytics.
    columns:
      - name: product_key
        description: Surrogate key for products.
        tests: [not_null, unique]

  - name: fact_sales
    description: >
      Fact table containing transactional sales data for analytics and reporting.
    columns:
      - name: order_number
        description: Unique order identifier.
        tests: [not_null]
      - name: customer_key
        description: Foreign key to `dim_customers`.
      - name: product_key
        description: Foreign key to `dim_products`.
      - name: quantity
        description: Number of products sold.
      - name: total_amount
        description: Total revenue generated by the order.

  - name: erp
    description: ERP seed sources for customer, location, and product category.
    tables:
      - name: CUST_AZ12
        description: ERP customer master

      - name: LOC_A101
        description: ERP location master

      - name: PX_CAT_G1V2
        description: ERP product category master
